spring:
  application:
    name: profi-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=profi
    username: postgres
    password: admin
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    default-schema: postgres
    liquibase-schema: public
    user: postgres
    password: admin
    change-log:

